services:
  geopagos.gateway.app:
    image: ${DOCKER_REGISTRY-}geopagosgatewayapp
    container_name: services-gateway
    hostname: services-gateway
    build:
      context: .
      dockerfile: GeoPagos.Gateway.App/Dockerfile
    networks:
      - geopagos-network

  geopagos.authorization.api:
    image: ${DOCKER_REGISTRY-}geopagosauthorizationapi
    container_name: services-authorization
    hostname: services-authorization
    build:
      context: .
      dockerfile: GeoPagos.Authorization.Api/Dockerfile
    networks:
      - geopagos-network


  geopagos.paymentprocessor.api:
    image: ${DOCKER_REGISTRY-}geopagospaymentprocessorapi
    container_name: services-payment-processor  
    hostname: services-payment-processor
    build:
      context: .
      dockerfile: GeoPagos.PaymentProcessor.Api/Dockerfile
    networks:
      - geopagos-network

  consul:
    image: consul:1.15.0  # Usar una versión específica
    container_name: services-consul 
    hostname: services-consul
    ports:
      - "8500:8500"  
    volumes:
      - consul-data:/consul/data
    networks:
      - geopagos-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: services-rabbitmq
    hostname: services-rabbitmq
    ports:
      - "5672:5672" # Puerto para comunicación con aplicaciones (AMQP)
      - "15672:15672" # Puerto para la interfaz web de administración
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - geopagos-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: services-jaeger
    hostname: services-jaeger
    ports:
      - "16686:16686" # UI de Jaeger
      - "6831:6831/udp" # Puerto del agente
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      - geopagos-network 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node  # Para usar Elasticsearch en un solo nodo
      - ELASTIC_PASSWORD=admin  # Contraseña para el usuario "elastic"
    ports:
      - "9200:9200"  # Puerto HTTP para interactuar con Elasticsearch
      - "9300:9300"  # Puerto para la comunicación interna entre nodos
    networks:
      - geopagos-network 

  kibana:
     image: docker.elastic.co/kibana/kibana:8.7.0
     container_name: kibana
     environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        - ELASTICSEARCH_USERNAME=admin
        - ELASTICSEARCH_PASSWORD=admin
     ports:
        - "5601:5601"  # Puerto de Kibana para acceder a la interfaz web
     networks:
      - geopagos-network 
     depends_on:
        - elasticsearch



volumes:
  consul-data:

networks:
  geopagos-network:  