services:
  geopagos.gateway.app:
    image: ${DOCKER_REGISTRY-}geopagosgatewayapp
    container_name: services-gateway
    hostname: services-gateway
    build:
      context: .
      dockerfile: GeoPagos.Gateway.App/Dockerfile
    ports:
      - "8001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - consul
      - geopagos.authorization.api
    networks:
      - geopagos-network

  geopagos.authorization.api:
    image: ${DOCKER_REGISTRY-}geopagosauthorizationapi
    container_name: services-authorization
    hostname: services-authorization
    ports:
      - "8002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: GeoPagos.Authorization.Api/Dockerfile
    networks:
      - geopagos-network

  geopagos.authorization.cron:
    image: ${DOCKER_REGISTRY-}geopagosauthorizationcron
    container_name: services-authorization-cron
    hostname: services-authorization-cron
    ports:
      - "8004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: GeoPagos.Authorization.Cron/Dockerfile
    networks:
      - geopagos-network


  geopagos.paymentprocessor.api:
    image: ${DOCKER_REGISTRY-}geopagospaymentprocessorapi
    container_name: services-payment-processor  
    hostname: services-payment-processor
    build:
      context: .
      dockerfile: GeoPagos.PaymentProcessor.Api/Dockerfile
    ports:
      - "8003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - geopagos-network

  consul:
    image: consul:1.15.0  # Usar una version especifica
    container_name: services-consul 
    hostname: services-consul
    ports:
      - "8500:8500"  
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    volumes:
      - consul-data:/consul/data
    networks:
      - geopagos-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: services-rabbitmq
    hostname: services-rabbitmq
    ports:
      - "5672:5672" # Puerto para comunicacion con aplicaciones (AMQP)
      - "15672:15672" # Puerto para la interfaz web 
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - geopagos-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver 
    environment:
      - NAME=AuthorizationDb
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyP@ssw0rd2025
    ports:
      - "1434:1433"
    networks:
      - geopagos-network 
    restart: always 






volumes:
  consul-data:
  es_data:
    driver: local
  sql_data:

networks:
  geopagos-network:  
